# Generated by Django 4.2.5 on 2024-02-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_services_masters'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.masters', verbose_name='выбор мастера')),
                ('service', models.ManyToManyField(to='service.services', verbose_name='выбор услуг')),
            ],
        ),
    ]
