# Generated by Django 5.0.1 on 2024-02-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название модели')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=120, verbose_name='телефон')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='описание')),
                ('call_time', models.CharField(blank=True, max_length=120, null=True, verbose_name='время звонка')),
            ],
            options={
                'verbose_name': 'форма обратной связи',
                'verbose_name_plural': 'формаы обратной связи',
            },
        ),
    ]
